### ISSUE TITLE
Duplicate theme directories/files?

### ISSUE THREAD

**Issue by open-risk** [Wirecloud/wirecloud#119]
In a fresh install of wirecloud with pip (on ubuntu) there are two sets of theme files generated, e.g.,
./wirecloud/defaulttheme
./lib/python2.7/site-packages/wirecloud/defaulttheme

With the exception of the __init__.py file, these directories are identical.
This is relevant for developing / modifying themes as per instructions here: https://wirecloud.readthedocs.org/en/stable/development/platform/themes/

It seems only the version in the site-package distribution is actually used by wirecloud?

**Comment by aarranz** [comment]
This is a duplicated of #114. The fix will be available in next releases 0.8.5 and 0.9.0.

Would be great if you can check if this has been fixed correctly as part of the work of #120.

Thanks :)
