### ISSUE TITLE
Installing development branch still reverts to Django 1.6

### ISSUE THREAD

**Issue by open-risk** [Wirecloud/wirecloud#120]
Installing development branch from sources as per https://wirecloud.readthedocs.org/en/stable/installation_guide/ using the following steps

* git clone git://github.com/Wirecloud/wirecloud.git
* cd wirecloud
* git checkout 0.8.x
* cd ./src
* Issue: python setup.py bdist_wheel  (there is a typo in docs here)
* Issue: setup.py has a line extras_require={python_version < '3.2'": ('futures>=2.1.3'} which I had to comment out to proceed
* pip install dist/wirecloud-0.8.4-py2.py3-none-any.whl

Produces the following at the end:

<pre>
Installing collected packages: Django
  Found existing installation: Django 1.9.1
    Uninstalling Django-1.9.1:
      Successfully uninstalled Django-1.9.1
Successfully installed Django-1.6.11
</pre>

**Comment by aarranz** [comment]
The main problem is that that instructions are for installing the latest release on the 0.8.x series.

> - git clone git://github.com/Wirecloud/wirecloud.git
> - cd wirecloud
> - git checkout 0.8.x
use `git checkout develop` here for switching to the develop branch
> - cd ./src
> - Issue: python setup.py bdist_wheel (there is a typo in docs here)
Thanks for reporting this :) will be fixed ASAP.
> - Issue: setup.py has a line extras_require={python_version < '3.2'": ('futures>=2.1.3'} which I had to comment out to proceed
Whats the problem with that line? It's working for me
> - pip install dist/wirecloud-0.8.4-py2.py3-none-any.whl
If everything goes well you should be able to install `dist/wirecloud-0.9.0a1-py2.py3-none-any.whl` ;-)

**Comment by aarranz** [comment]
Regarding:

> - Issue: setup.py has a line extras_require={python_version < '3.2'": ('futures>=2.1.3'} which I had to comment out to proceed

Seems that `wheel` >= 0.24 is required for this.

**Comment by aarranz** [comment]
And `setuptools` >= 18.5

**Comment by open-risk** [comment]
Using the development branch helped :+1:  The issue with the setup file exception persists with Wheel version 0.26, easy_install/setuptools  3.3 (the latest on the ubuntu distribution). Will be doing some more testing now

**Comment by aarranz** [comment]
great news :+1:

Remember that you can upgrade your setuptools module using pip/easy_install (maybe in a virtualenv):

```
pip install -U setuptools
```

Thanks for testing it :)

**Comment by open-risk** [comment]
Yep, it was due to setuptools in the end...
