### ISSUE TITLE
Wiring view bug with no image widgets/operators

### ISSUE THREAD

**Issue by Mognom** [Wirecloud/wirecloud#125]
If a Widget/Operator has no image, in the wiring editor tries to load an image but without success:

![screenshot from 2016-02-15 11 50 40](https://cloud.githubusercontent.com/assets/6499837/13046926/8da314a4-d3d3-11e5-9655-13b2598514c0.png)

Note: on the "My resources" view Wirecloud displays a "no image available" message.

**Comment by aarranz** [comment]
This bug happens on Firefox, chrome seems to work.
