### ISSUE TITLE
Max num of POI displayed in Map Viewer?

### ISSUE THREAD

**Issue by reciomario** [Wirecloud/wirecloud#126]
I am developing an application where the Map Viewer is connected with my Orion Data Context Broker, but it seems that only represents in the map 20 POI (when I have stored in my Orion more than 600...) Is there a limit? Should I configure anything?

**Comment by aarranz** [comment]
There is not a maximum number of PoIs, but the NGSI source operator currently only retrieves 20 entities from the context broker from the beginning. This operator will load more entities if they are modified and the context broker sends a notification with the updates.

I have created a ticket in the NGSI operator issue tracker (wirecloud-fiware/ngsi-source-operator#7) for fixing this problem.
