### ISSUE TITLE
Backspace key does not work on number type preferences.

### ISSUE THREAD

**Issue by Mognom** [Wirecloud/wirecloud#141]
When trying to give a new value to a preference with a number type, the Backspace key does not delete characters. This happens when the preference is of type "number" and not when its of type "text".

Note: the delete key does work, and the value can be overwritten by selecting it and typing a new value, as expected.
Note2: I've not tested if this does happen or not for the other preference types, such as password or boolean.

**Comment by aarranz** [comment]
The backspace key is not capture and has no meaning when pressed over a boolean field. Password fields are working correctly.
