### ISSUE TITLE
Connections should not be added to the current behaviour when modified

### ISSUE THREAD

**Issue by aarranz** [Wirecloud/wirecloud#153]
Currently, if you modify a connection that not forms part of the current behaviour...

<img width="697" alt="captura de pantalla 2016-04-15 a las 17 18 24" src="https://cloud.githubusercontent.com/assets/841201/14566068/3c640d02-032e-11e6-89e8-6b6a901767c2.png" srcset="https://cloud.githubusercontent.com/assets/841201/14566068/3c640d02-032e-11e6-89e8-6b6a901767c2.png 2x">

... WireCloud will show a dialog telling you that if you continue, the connection will be changed also in the rest of behaviours:

<img width="568" alt="captura de pantalla 2016-04-15 a las 17 18 38" src="https://cloud.githubusercontent.com/assets/841201/14566107/64e9f71e-032e-11e6-83ce-a9f806a04d4c.png" srcset="https://cloud.githubusercontent.com/assets/841201/14566107/64e9f71e-032e-11e6-83ce-a9f806a04d4c.png 2x">

This will lead to this connection being added to the current behaviour:

<img width="663" alt="captura de pantalla 2016-04-15 a las 17 18 58" src="https://cloud.githubusercontent.com/assets/841201/14566171/b5631b44-032e-11e6-8767-833faf809c10.png" srcset="https://cloud.githubusercontent.com/assets/841201/14566171/b5631b44-032e-11e6-8767-833faf809c10.png 2x">

But in fact, it should not ask, and assume that what you want is to change the connection in the other behaviours without adding it to the current one.

**Comment by jpajuelo** [comment]
Actually, the main function of the behaviour engine is to ensure that every change made during the edition of the wiring only affects to the active behaviour.

Explained this, I think the best solution is that the modification of a connection which does not belong to the active behaviour should not be allowed.

Even so, an improvement of the wiring editor to modify the wiring and at the same time, to change to another behaviour easily, would be necessary.

The pull-request #167 make the enough changes to achieve this scenario.
