### ISSUE TITLE
Improve log managers

### ISSUE THREAD

**Issue by jpajuelo** [Wirecloud/wirecloud#193]
With regard to the **log managers**, there are some features that should be improved. These would be the following:
- Every log has a title, a description and a creation date, that said the title should be short and the description should be an explanation detailed of the issue and also show solutions.
- Improve the style of the logs.
- Improve the cycles because they are not working very well.
- Improve the hierarchy of the log managers because sometimes some issues are repeated.
- It could be interesting when you see the window menu of the logs, in the first instance you only see the logs of the current cycle.
- Add logs of type 'success'. Because some info logs should be success logs.
- It would make no sense to create more classes of LogManager since the LogWindowMenu should be more editable. For example, the title of the window menu should be a constructor's argument.

**Comment by aarranz** [comment]
Too much things to be tackled in a single ticket... 

Also, some of the points are not documented enough (e.g the "Improve the cycles because they are not working very well." has no references to what is not working well...)
