### ISSUE TITLE
Wire customize option nor working.

### ISSUE THREAD

**Issue by Mognom** [Wirecloud/wirecloud#196]
The Wiring View customize option of the wires (conections between componenets) no longer works.
When attempting to use it, it displays both drag points, but they can't be dragged.

**Comment by aarranz** [comment]
Please, provide more info (version, browser, etc..) because I cannot reproduce it. I've tested my development version, `https://mashup.lab.fiware.org`, ... and they seems to be working as expected.

**Comment by Mognom** [comment]
It's fixed in the latest version of Wirecloud
