### ISSUE TITLE
Weather Mashup Example dont works

### ISSUE THREAD

**Issue by fermenreq** [Wirecloud/wirecloud#260]
Hi all ! 

Im working wiith the Wirecloud Installation Guide, specifically at this point : [http://wirecloud.readthedocs.io/en/stable/installation_guide/#sanity-check-procedures](http://wirecloud.readthedocs.io/en/stable/installation_guide/#sanity-check-procedures)

When I upload  "CoNWeT_weather-mashup-example_1.0.2.wgt" into the platform, I get the following error: 

**Error uploading the following components:
    CoNWeT_weather-mashup-example_1.0.2.wgt: Invalid embedded file: macs/CoNWeT_wms-viewer-geowidget_0.5.5.wgt**

I supposed that was an old version, I tried with other mashup and its works. Where can I find a weather mashup example that its works ? 

Thanks in advance!

**Comment by manchandavishal** [comment]
fixed in #341
