### ISSUE TITLE
NGSI API v2

### ISSUE THREAD

**Issue by etatus** [Wirecloud/wirecloud#263]
Do you plan to update the NGSI.js API to Orion API v2?. Version v1 is very limited. Specifically, the updateContext function treat all the attributes to update as strings.

**Comment by aarranz** [comment]
Hi @etatus, we are working on updating the NGSI bindings to API v2, but is not ready yet, sorry. Anyway, the `updateContext` method should be able use [structured values](http://fiware-orion.readthedocs.io/en/master/user/structured_attribute_valued/) (v1 of the NGSI API allows it). I'm checking if there is a problem in the implementation and I will update you about this regard.

**Comment by aarranz** [comment]
Hi @etatus, I have checked it, and the NGSI API is working for structured values, the only thing to take into account is that the NGSI v1 converts leaf nodes into strings. You can follow the progress in adding NGSI v2 support in this the conwetlab/ngsijs#9 ticket

**Comment by etatus** [comment]
Thank you for your answer. I'm developing a widget to allow editing attributes, and API v1 not only treats all attributes as strings but also requires "type": "StructuredValue" for complex (structured) attributes. Therefore, attributes from a GeoJSON object ("type":"geo:json") cannot be updated.

Do you have a roadmap to know when the "Update entity attributes" / "Update attribute" functions will be available?

**Comment by aarranz** [comment]
We are working on adding NGSIv2 support to the `ngsijs` library. I think that is very feasible to have a first/initial implementation (supporting all the elements listed in the conwetlab/ngsijs#9 ticket) ready by the next week. Then we have to release a new version of WireCloud using the new version of the library.

**Comment by etatus** [comment]
Great news! Thank you very much.
