### ISSUE TITLE
How to set up a development environment?

### ISSUE THREAD

**Issue by brylie** [Wirecloud/wirecloud#292]
As a new Django/Wirecloud developer, I would appreciate a step-by-step guide to setting up a Wirecloud development environment. Ideally, the environment would allow me to make changes to Wirecloud core and user interface with minimal time between edit and output (quick validation/failure).

What steps are involved to set up a Wirecloud development environment?

**Comment by aarranz** [comment]
Hi @brylie,

I have updated the contribution guide, please have a look into the new documentation (especially to the new [Contributing code](https://github.com/Wirecloud/wirecloud/blob/develop/docs/CONTRIBUTING.md#contributing-code) section) and tell us if you miss something.

Thanks for your contributions 😄

**Comment by brylie** [comment]
Most excellent! For what it's worth, Mozilla have written a guide called [How to Build a CONTRIBUTING.md](http://mozillascience.github.io/working-open-workshop/contributing/). There may be some additional details from the Mozilla example that would be nice to have in the Wirecloud contributing guide.

Great work in any case :-)

**Comment by aarranz** [comment]
Thanks for the reference to the Mozilla documentation. I will try to improve documentation using it 😄.

I'm closing this ticket as, in general, seems fixed. Anyway, do not hesitate to tell us if you see something to improve 😉.
