### ISSUE TITLE
Can't add marketplace

### ISSUE THREAD

**Issue by osfrance** [Wirecloud/wirecloud#299]
Hi, I can't add fiware marketplace like in the userguide, the url https://marketplace.lab.fiware.org don't exist.
(I try https://marketplace.fiware.org but it's not work)

How i can add a marketplace for following the user guide?

Thanks,

**Comment by brylie** [comment]
I was also having trouble figuring out how to add the marketplace. Subscribing to this issue.

**Comment by osfrance** [comment]
Hi Brylie, I installed widget manually by subscribe and download them from fiware portal and uploading to my wirecloud private instance, but I have other problems like API key from google maps ... ("Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys") when using maps-viewer-widget ...

**Comment by brylie** [comment]
@osfrance it might be good to open a separate issue for the Google Maps warning. That way, we can get support from the widget maintainer. Can you point me to the source repository for the Google Maps widget?

**Comment by brylie** [comment]
@aarranz the question regarding the FIWARE marketplace may become increasingly relevant. Would it be possible to document what is involved with adding the FIWARE repository to a local Wirecloud instance?

**Comment by brylie** [comment]
By way of example, I registered on `mashup.lab.fiware.org` and can't figure out how to add resources from the FIWARE marketplace:

![screenshot_20170803_103550](https://user-images.githubusercontent.com/17307/28911014-a6488476-7837-11e7-9b78-08b5bf88337c.png)

**Comment by osfrance** [comment]
Hi Brylie,
I've allready sent a issue to map-viewer-widget: https://github.com/Wirecloud/map-viewer-widget/issues/4
Thanks for your help,
