### ISSUE TITLE
server hiccups on apache2.4

### ISSUE THREAD

**Issue by raquelmeloalmeida** [Wirecloud/wirecloud#306]
Hi,

I am following the installation guide to install wirecloud on my vbox running ubuntu 16.04. 
When i go to wirecloud running it on django i am able to login my user and the page is redirected to the wirecloud/home, but when using apache2.4 it is not able to login the user and keep giving 500 server error with server hiccup. 

Any ideia why this happens? 

Thks

**Comment by aarranz** [comment]
Hi @raquelmeloalmeida,

WireCloud should work using apache 2.4. Please, set the `DEBUG` setting to `True` in the `settings.py` file and try again to access WireCloud using a browser. You should see a detailed error message.

Best regards.

**Comment by raquelmeloalmeida** [comment]
Permission issues!

Thks!
