### ISSUE TITLE
Isn't it similar to Apache Shindig and Google Gadget ?

### ISSUE THREAD

**Issue by rajjanorkar** [Wirecloud/wirecloud#311]
Isn't this project similar to Apache Shindig 

https://github.com/apache/shindig

And google gadget API? 

https://developers.google.com/gadgets/

**Comment by rajjanorkar** [comment]
any feedback on this?

**Comment by brylie** [comment]
There may be some similarities, such as that Google Gadgets are HTML widgets. What similarities do you notice?

There are also some differences, such as that Wirecloud provides a visual data programming language that wires widgets together and sends data between them.

> Apache Shindig's goal is to allow new sites to start hosting social apps in under an hour's worth of work.

The goal of Apache Shindig is related to hosting social apps, whereas Wirecloud is designed, more broadly, to be a "web application mashup platform".

**Comment by brylie** [comment]
What similarities and differences do you notice?

**Comment by mjimenezganan** [comment]
Hi,

Both share the idea of packaging interface snippets (view and functionality) as widgets, based on web technologies.

Besides that, WireCloud goes much beyond and serves for creating composite applications from a set of widgets (and operators, which do only have functionality), empowering users to confgure, modify, create their own application.

The biggest difference is the communication capabilities in WireCloud (called wiring), with a powerful tool to create multiple channels, and with output and inputs in widgets and operators (so no longer widgets are expected to work on their own, but collaborating with other components in an asyncrhonous way).

Widget preferences, access to different level of properties, sharing dashboards, embedding dashboards and some others are also features outperforming Apache Shindig, Open Social specs and Google Gadget API, which seem to have been discontinued for the last 5 years.

Best regards
