### ISSUE TITLE
Its wirecloud support nsgi 2?

### ISSUE THREAD

**Issue by Efeyabel** [Wirecloud/wirecloud#318]
I see its supports v1, but i cant find any support on v2.

Its already support nsgi 2?

**Comment by aarranz** [comment]
Yes, WireCloud uses the [ngsijs](https://github.com/conwetlab/ngsijs) library to provide NGSI support and this library supports NGSIv2, but take into account that you must use at least WireCloud v1.1 to use a recent version of that library.
