### ISSUE TITLE
Error trying to load the workspace in Chrome

### ISSUE THREAD

**Issue by flopezag** [Wirecloud/wirecloud#324]
When I try to open my workspace in Chrome brower I get the following error:

![image](https://user-images.githubusercontent.com/1379796/40169810-21a46786-59c7-11e8-9333-ff019542c49d.png)

But if I open it on a Firefox browser, I have no problem.

**Comment by aarranz** [comment]
Hi @flopezag!

It is going to be very hard to fix this without more details. In general WireCloud is working on Chrome, so we need more details to solve this. can you provide us more details from the Chrome developer tools? E.g. there is any logged exception? is any ajax request failing?

Cheers

**Comment by flopezag** [comment]
I see 2 errors in the page:

Request URL: https://mashup.lab.fiware.org/api/workspaces
Request Method: GET
Status Code: 406 Not Acceptable
Remote Address: 130.206.84.11:443
Referrer Policy: no-referrer-when-downgrade

Response:
{"description": "The requested resource is only capable of generating content not acceptable according to the Accept headers sent in the request", "details": {"supported_mime_types": ["application/json"]}}

And

Request URL: https://mashup.lab.fiware.org/api/resources
Request Method: GET
Status Code: 406 Not Acceptable
Remote Address: 130.206.84.11:443
Referrer Policy: no-referrer-when-downgrade

Response:
{"description": "The requested resource is only capable of generating content not acceptable according to the Accept headers sent in the request", "details": {"supported_mime_types": ["application/json"]}}

**Comment by aarranz** [comment]
This is strange as Chrome should make requests using valid `Accept` headers. Could you provide us all the `Accept` headers used by Chrome (`Accept`, `Accept-Charset`, `Accept-Encoding`, etc) when making those requests?

**Comment by flopezag** [comment]
Oh you gave me an important clue. I had a plugin to change the Accept of the browser (text/plain). But probably should be great if this error should be reported in order to resolve the issue in a faster way.
