### ISSUE TITLE
Unable to select Groups in shared window

### ISSUE THREAD

**Issue by flopezag** [Wirecloud/wirecloud#330]
When I tried to select the user or group from the option "Users and groups with access" I cannot see the groups that I have created in the Django Admin panel. The Wirecloud only shows me the list of available users.

**Comment by aarranz** [comment]
Seems to be working on develop, but not on the 1.1 version

**Comment by aarranz** [comment]
Analysing this a bit more in details, the problem is that is not enough to create Django Groups, those groups have to be linked to an Organization user. PR #335 added a new command for creating those organizations. There are still problems when adding them into the search indexes.

**Comment by aarranz** [comment]
PR #336 fixed mayor problems regarding updating the search index. Those changes have been backported to v1.1, so I'm going to make a v1.1.2 release.
