### ISSUE TITLE
OAuth2 redirect_uri & FORCE_PORT

### ISSUE THREAD

**Issue by fiware-austria** [Wirecloud/wirecloud#359]
Hi @aarranz!

I'm currently working on fixing the FORCE_PORT/settings.py-read-only issue for the docker image.
Unfortunately I ran into another issue that seems to be related. Maybe it's only because I've missed something in the documentation?

Here's the problem:

As already pointed out, we are running wirecloud behind a nginx reverse proxy that is exposed as a kubernetes LoadBalancer service. Whenever I try to login via OAuth/Keyrock I get a `redirect_uri` with the wrong port number and `FORCE_PORT` seems to get ignored. Is there anything I could do about this?
A quick response would be very helpful!

BTW: Will you be at the FIWARE Summit next week?

**Comment by aarranz** [comment]
Hi @fiware-austria,

Integration with the KeyRock is done using [python-social-auth](https://python-social-auth.readthedocs.io/en/latest/), in this sense, we know that there are some problems integrating the `FORCE_*` settings as the url is, in those cases, build inside python-social-auth's code ignoring WireCloud's settings.

That said, docker image is configured by default to allow the use of the `X-Forwarded-*` headers sent by load balancers (more specifically, the headers configured on the docker image are: `X-Forwarded-Proto`, `X-Forwarded-Host` and `X-Forwarded-Port`). We have done some deployments using WireCloud 1.2.0 docker image behind load balancers and they are working without any problem but, if you continue having problems, you should read [python-social-auth's documentation](https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html?highlight=https#processing-redirects-and-urlopen) to search for any configuration setting that can be of help.

Sorry but, due personal reasons, I'm not going to attend the FIWARE Summit next week. You can talk with @mjimenezganan and @fdelavega, who will attend the event 😄.

**Comment by fiware-austria** [comment]
Hi @aarranz!

Thanks a lot for your quick support. I hat to add `proxy_set_header X-Forwarded-Host $host:30080;` to `nginx.conf` and now it works.

**Comment by aarranz** [comment]
Great 😄, then I'm closing this ticket.
