### ISSUE TITLE
[SHOULD] Repo description, topics and URL link

### ISSUE THREAD

**Issue by jason-fox** [Wirecloud/wirecloud#365]
Please click the edit button at the head of the repo and amend the description link and topics as shown (or similar):

### Link

> https://wirecloud.rtfd.io/

- SHOULD requirement from the TSC.

**Comment by aarranz** [comment]
I have configured `https://wirecloud.rtfd.io/` as the website link, is this acceptable?

**Comment by jason-fox** [comment]
Yes,  that link is fine. Closing as completed.
