### ISSUE TITLE
[SHOULD] Every GE should have tutorial information

### ISSUE THREAD

**Issue by jason-fox** [Wirecloud/wirecloud#369]
At the moment Wirecloud has a information in the Academy and fulfils the minimum Training section requirements. This is a placeholder to ensure a simple Wirecloud hello world gets added to the Step-by-Step tutorials at some point

* Presence of a tutorial is a SHOULD requirement

**Comment by jason-fox** [comment]
I believe that you already have some seed code for a tutorial, if so could you pass it on and assign this to me task to me.

It  still makes sense to create an issue however and leave it open so it doesn't get lost.

**Comment by mjimenezganan** [comment]
I'm preparing two tutorials:

1. Basic tutorial. I'd rather don't replicate all in the user-guide, but create a basic tutorial with information on how to deploy with docker, integrate with IdM, use variables and volumes for easy deployment, and basic usage, are you OK?. 
2. Data visualization tutorial, focused on NGSI data, essentially, what was shown at Malaga, at least for NGSI. It might cover data from CKAN data-store or other sourcer, but it is unsure. I'd like to include the wizard widget, but untill now it does only run through CKAN, and entering CKAN seems quite out of scope. Probably I'll update such components and make it usable standalone, and include here.

Draft is on https://github.com/mjimenezganan/wirecloud-tutorials, but only the basic one has readable content.

**Comment by jason-fox** [comment]
Completed: https://github.com/FIWARE/tutorials.Application-Mashup
