### ISSUE TITLE
Confirm License

### ISSUE THREAD

**Issue by jason-fox** [Wirecloud/wirecloud#372]
The FOSSA Bot is raising an issue against the licensing of a dependency of this project.
I think it's probably OK, but could you confirm that the licensing of the following sub-module is OK?

```
github.com/Wirecloud/wirecloud  wirecloud-markdown-github
```

I think the issue is the non-standard exception clause. Is it needed or could a standard License be used instead. I just want to check that this isn't a [crayon license](https://opensource.stackexchange.com/questions/1445/how-can-a-crayon-license-be-a-problem) and the component can be used for Open Source

**Comment by mjimenezganan** [comment]
The exception is required so as the obligations to share contributions are not extended to the linked elements, which are widgets and operators. Therefore, the platform itself is ruled by the Affero GPL, but domain-specific widgets and operators, created from scratch or by extension, are not obliged to be published, so proprietary components can be created to be deployed within WireCloud.

The exception is the way we found for addressing this intention.

**Comment by aarranz** [comment]
Hi Jason,

So, the FOSSA bot is complaining over the `wirecloud-markdown-github` dependency, is this correct?

In this sense, I can confirm you that the `wirecloud-markdown-github` dependency is fine. On the one hand it is provided by the WireCloud team, on the other hand it is used only for building documentation, so it is not affecting WireCloud execution.

Moreover, this module was a hack for being able to use the PyMdown Extensions before they were released (we use them to use GFM with MkDocs), but we are moving to use them directly. [License](https://facelessuser.github.io/pymdown-extensions/license/) for those extension is fully compatible with WireCloud/MkDocs and so on, so I don't see any problem.

**Comment by jason-fox** [comment]
OK, so effectively this is a false positive from FOSSA Bot. I'll close.
