### ISSUE TITLE
widget development workflow

### ISSUE THREAD

**Issue by pedrokost** [Wirecloud/wirecloud#40]
What is the recommended workflow for widget development? The tutorials I see online seem to invite developers to zip-rename-upload the developing widget to test them out. 

Is there a way to develop and test the widgets by circumventing all this zip-upload business? Or has anyone developed editor plugins to automate this process?

**Comment by aarranz** [comment]
Hi pedrokost,

please, use [StackOverflow](http://stackoverflow.com/questions/tagged/fiware-wirecloud) for asking your questions about WireCloud, this issue tracker is used for requesting new features or reporting bugs.

I will answer you asap as you post this question on StackOverflow.

Best regards.
Álvaro

**Comment by pedrokost** [comment]
@aarranz, I have posted the question on [StackOverflow](http://stackoverflow.com/questions/29555947/widget-development-workflow) as you suggested.
