### ISSUE TITLE
Widget height is horribly long after switching from column to grid layout

### ISSUE THREAD

**Issue by jonadev95** [Wirecloud/wirecloud#41]
After switching from the column layout to the grid layout, the widget height is terribly long.All other widgets on the workspace will be kicked to the bottom of the page, which means a lot of scrolling to bring them back in the right position.

Example: 

Height after adding in column-layout:
![column_layout](https://cloud.githubusercontent.com/assets/4764029/6554725/1c99c8fc-c65f-11e4-837d-a24aab46590d.png)

Height after adding in grid-layout: (Scroll bar)
![grid_layout](https://cloud.githubusercontent.com/assets/4764029/6554578/9d030ce4-c65d-11e4-9a64-87269bd52ace.png)

**Comment by aarranz** [comment]
Commits f6bc323fcfe9be11749e842c4af8e934a0b46498 and 41c560cbdfaa4b762538338e56f5366fa3e964cd add initial support for using `px` and `%` units in the `config.xml` file for indicating the initial widget size.

**Comment by aarranz** [comment]
This will be available on WireCloud 0.8.0.
