### ISSUE TITLE
Postgres error: the server must be started by the user that owns the data directory

### ISSUE THREAD

**Issue by spanishkangaroo** [Wirecloud/wirecloud#449]
Using the provided docker-compose.yml and nginx.conf files, the stack fails by throwing the following error:

`FATAL: data directory “/var/lib/postgresql/data/pgdata” has wrong ownership`
`HINT: The server must be started by the user that owns the data directory.`

The issue is easily solved by replacing the volumen part in the postgres definition with:

`volumes:
            - /var/lib/postgresql/data`

Regards,

**Comment by aarranz** [comment]
Hi @spanishkangaroo,

Thanks four your #450 PR. As talked on that thread, this were related to some problems that raises when using docker on windows. Those problems should now be solved as we merged your PR.

Thank for your contribution
