### ISSUE TITLE
Page rendering error

### ISSUE THREAD

**Issue by Neeraj-Nec** [Wirecloud/wirecloud#469]
![ErrorScreenshot](https://user-images.githubusercontent.com/50608116/74215233-66ca7000-4cc6-11ea-86a6-9896eb6635cc.png)

**Comment by fisuda** [comment]
See https://github.com/Wirecloud/wirecloud/issues/461 and [bug-reports](https://github.com/Wirecloud/wirecloud/blob/develop/docs/CONTRIBUTING.md#bug-reports)

**Comment by aarranz** [comment]
Closing, as the problem seems to be related to the problem linked by @fisuda. In any case, if you still have problems, you're welcome to reopen this ticket 😄.
