### ISSUE TITLE
Wirecloud browser support

### ISSUE THREAD

**Issue by marcinbudny** [Wirecloud/wirecloud#47]
What are the web browsers supported by Wirecloud? I was not able to find this information in the documentation.

**Comment by aarranz** [comment]
We officially support Chrome and Firefox, as we pass our selenium tests using those browsers. I cannot tell you concrete versions now, but we are working on the documentation and I will try to provide you a more detailed response ASAP.

**Comment by aarranz** [comment]
Sorry for the delay, but finally we have a list of supported browsers: https://wirecloud.readthedocs.org/en/latest/user_guide/#supported-browsers
