### ISSUE TITLE
Can't create an EventSource Object in Microsoft Edge (EdgeHTML)

### ISSUE THREAD

**Issue by fisuda** [Wirecloud/wirecloud#482]
This error occurs in a widget which uses the ngsijs library and creates NGSI Subscription. e.g. NGSI Source operator.

![ng](https://user-images.githubusercontent.com/31051904/77705065-0a1ade80-7002-11ea-80ff-15d0529a82eb.png)

```
Error retrieving subscription in the context broker server: You aren't allowed to use the WireCloud's proxy. Have you signed off from WireCloud?
Error checking subscription in the context broker server: You aren't allowed to use the WireCloud's proxy. Have you signed off from WireCloud?
Error creating subscription in the context broker server: 'EventSource' is not defined
```

Microsoft Edge (EdgeHTML) can pass the check of basic requirements. But, it fails to create a EventSource Object in NGSI.js. It seems that It doesn't support Server-Sent Events (EventSource).

https://developer.microsoft.com/en-us/microsoft-edge/status/serversenteventseventsource/

![image](https://user-images.githubusercontent.com/31051904/77705635-911c8680-7003-11ea-817c-4cdb0c3e65d5.png)

- Microsoft Edge (EdgeHTML) version on Windows 10 Pro 1909
    Microsoft Edge 44.18362.449.0
    Microsoft EdgeHTML 18.18363

**Comment by aarranz** [comment]
Hi @fisuda,

Thanks for reporting this problem. We are considering moving `ngsi-proxy` to use websockets, although this is not going to be done on the short time. So we should find some alternative for now.

At this moment, I think we have two options:
1. Merging you PR and make clear that Microsoft Edge (at least EdgeHTML) is not supported.
2. Try to use some `EventSource` polyfill (e.g. https://www.npmjs.com/package/event-source-polyfill). Here the point is that Microsoft Edge is not one of the browsers supported by WireCloud as Travis CI tests are not being executed using this browser (some kind of service like https://saucelabs.com/ is needed to be able to execute Microsoft Edge while running the tests).

I don't know if you think it is worth to analyse point 2. If you don't matter on Microsoft Edge, we can just merge your PR.

**Comment by fisuda** [comment]
Hi @aarranz,

Thank you for your comment. I don't matter on Microsoft Edge (EdgeHTML). I just want to avoid that a user accesses to WireCloud with it. And also it's already a legacy product. I think that it is not necessary to support it.

Thanks
