### ISSUE TITLE
Requesting WireCloud Username and Password for Local Installation

### ISSUE THREAD

**Issue by fatemedbghi** [Wirecloud/wirecloud#531]
I recently installed WireCloud on my localhost using Docker, but I'm facing difficulties signing in as I don't know the username and password for the initial administrator account. I have tried the default credentials (admin/admin), but they do not seem to work.

Could you please provide me with the correct username and password to access the WireCloud instance deployed on my localhost?

**Comment by fdelavega** [comment]
You can create your initial admin user using the Wirecloud admin commands. In particular there is a createsuperuser one.

They are documented in WireCloud administration guide:
https://wirecloud.readthedocs.io/en/stable/administration_guide/
