### ISSUE TITLE
Quickstar conf rise Internal Server Error

### ISSUE THREAD

**Issue by darofar** [Wirecloud/wirecloud#54]
Hi there, I'm trying to familiarize myself with Wirecloud starting with quickstart option as it is shown in the documentation.

```
wirecloud-admin startproject wirecloud_instance --quick-start
```
But i got this error: 

```
mod_wsgi (pid=19541): Exception occurred processing WSGI script '/opt/quickly/quickly/wsgi.py'.
Traceback (most recent call last): ...
ImportError: Could not import settings 'quickly.settings' (Is it on sys.path? Is there an 
import error in the settings file?): No module named wirecloud.commons.utils.conf
```
I followed the steps of [Administration and Installation Guide](http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/Application_Mashup_-_Wirecloud_-_Installation_and_Administration_Guide#Introduction) and have configured my local instance over Apache 2.4 server

PD: sorry i dont know how to assign Doubt label.

**Comment by aarranz** [comment]
Check the `python-path` parameter used in the `WSGIDaemonProcess` directive, you should use something similar to:

```ApacheConf
    WSGIDaemonProcess wirecloud python-path=/opt/quickly
```

**Comment by aarranz** [comment]
Any progress?

We have updated the installation guide (and moved it to [Read the Docs](https://wirecloud.readthedocs.org/en/latest/installation_guide/#running-wirecloud-using-apache-2)), give it a try if you continue having problems.

Best regards

**Comment by darofar** [comment]
Hi Alvaro, thanks for the update.

We have to moved on because couldn't get finally fixed. i think the installation got corrupted, maybe some dependency or something like that. I want to start again from scratch in a new VM but need to fin the time for that! 

Ill let you know if finally i could get Wirecloud up an running. 

Thank you very much.

**Comment by aarranz** [comment]
ok, no problem :)
